:leaf: false

model:
  kwargs:
    num_classes: 1000
  outputs:
    - logits
  adapters:
    - type: LoadWeights
      skip_resumption: true
      from_url:
        url: "https://download.pytorch.org/models/densenet121-a639ec97.pth"
        cache_path: torchvision
      kwargs:
        is_torchvision_densenet: true
    - type: WidenLinearLayer
      kwargs:
        index: classifier
        new_features: 225

optimizer:
  type: SGD
  kwargs:
    lr: 0.002
    momentum: 0.9
    weight_decay: 0.00004

num_epochs: 50

scheduler:
  type: CosineAnnealing
  kwargs:
    T_max: 50

datasets:
  evaluations:
    global:
      type: ImageFolders
      kwargs:
        paths:
          - imagenet/val

    local:
      type: ImageFolders
      kwargs:
        paths:
          - 225-bird-species/valid

checkpoint:
  max_checkpoints: 1
  save_on_better_metric:
    field: "inferer/validation/metric/top_1"

objective:
  type: CrossEntropyLoss

metric:
  type: TopKAccuracy
  kwargs:
    ranks: [1, 5]
