:leaf: true

datasets:
  training:
    type: ExtendedImageFolders
    partitions:
      - path: imagenet/train
        ratio: 0.001
      - path: cars/train
        ratio: 1.000

  validation:
    type: ExtendedImageFolders
    partitions:
      - path: imagenet/val
        ratio: 0.001
      - path: cars/test
        ratio: 1.000
